In [1]:
import  pandas as pd
import numpy as np

In [25]:
data = pd.read_csv('../data/ChargingRecords.csv')
print(data)

       UserID  ChargerID  ChargerCompany            Location  ChargerType  \
0           0          1               1               hotel            0
1           0          1               1               hotel            0
2           0          1               1               hotel            0
3           0          1               1               hotel            0
4           0          1               1               hotel            0
...       ...        ...             ...                 ...          ...
72851    2155       2649               0  public institution            0
72852    2379       2670               0         sightseeing            1
72853    2388       2670               0         sightseeing            1
72854    2388       2671               0             company            1
72855    2388       2671               0             company            1

         StartDay StartTime      EndDay   EndTime     StartDatetime  \
0      2022-09-15  20:54:02  2022-09-15  23:59:13  2022-09-15 20:54
1      2022-09-14  20:01:05  2022-09-14  21:31:04  2022-09-14 20:01
2      2022-09-14  18:54:30  2022-09-14  19:54:29  2022-09-14 18:54
3      2022-09-29  18:32:51  2022-09-30   0:16:42  2022-09-29 18:32
4      2022-09-25  19:30:15  2022-09-26   0:30:14  2022-09-25 19:30
...           ...       ...         ...       ...               ...
72851  2022-01-27   9:54:44  2022-01-27   9:58:57   2022-01-27 9:54
72852  2021-10-31  14:52:11  2021-10-31  15:20:28  2021-10-31 14:52
72853  2021-10-03  13:52:14  2021-10-03  14:32:13  2021-10-03 13:52
72854  2021-11-18  11:37:44  2021-11-18  11:45:37  2021-11-18 11:37
72855  2021-10-30  17:29:02  2021-10-30  17:36:47  2021-10-30 17:29

            EndDatetime  Duration  Demand
0      2022-09-15 23:59       185   20.36
1      2022-09-14 21:31        90   10.19
2      2022-09-14 19:54        60    6.78
3       2022-09-30 0:16       344   37.65
4       2022-09-26 0:30       300   33.81
...                 ...       ...     ...
72851   2022-01-27 9:58         4    0.50
72852  2021-10-31 15:20        28   16.53
72853  2021-10-03 14:32        40   12.20
72854  2021-11-18 11:45         8    3.80
72855  2021-10-30 17:36         8    3.67

[72856 rows x 13 columns]

In [ ]:
data.tail(5)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
72851,2155,2649,0,public institution,0,2022-01-27,9:54:44,2022-01-27,9:58:57,2022-01-27 9:54,2022-01-27 9:58,4,0.50
72852,2379,2670,0,sightseeing,1,2021-10-31,14:52:11,2021-10-31,15:20:28,2021-10-31 14:52,2021-10-31 15:20,28,16.53
72853,2388,2670,0,sightseeing,1,2021-10-03,13:52:14,2021-10-03,14:32:13,2021-10-03 13:52,2021-10-03 14:32,40,12.20
72854,2388,2671,0,company,1,2021-11-18,11:37:44,2021-11-18,11:45:37,2021-11-18 11:37,2021-11-18 11:45,8,3.80
72855,2388,2671,0,company,1,2021-10-30,17:29:02,2021-10-30,17:36:47,2021-10-30 17:29,2021-10-30 17:36,8,3.67

In [30]:
data.head(5)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  object
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  object
 6   StartTime       72856 non-null  object
 7   EndDay          72856 non-null  object
 8   EndTime         72856 non-null  object
 9   StartDatetime   72856 non-null  object
 10  EndDatetime     72856 non-null  object
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), object(7)
memory usage: 7.2+ MB

In [44]:
print(data.describe(include='all'))

              UserID     ChargerID  ChargerCompany     Location  ChargerType  \
count   72856.000000  72856.000000    72856.000000        72856  72856.00000
unique           NaN           NaN             NaN           14          NaN
top              NaN           NaN             NaN  public area          NaN
freq             NaN           NaN             NaN        14082          NaN
mean      338.164667    525.489212        0.627443          NaN      0.20524
std       553.970996    569.544469        0.483489          NaN      0.40388
min         0.000000      1.000000        0.000000          NaN      0.00000
25%         0.000000    107.000000        0.000000          NaN      0.00000
50%        62.000000    301.000000        1.000000          NaN      0.00000
75%       407.000000    738.000000        1.000000          NaN      0.00000
max      2501.000000   2671.000000        1.000000          NaN      1.00000

          StartDay StartTime      EndDay  EndTime     StartDatetime  \
count        72856     72856       72856    72856             72856
unique         366     43245         365    46710             65628
top     2022-08-10  19:04:30  2022-07-28  4:10:01  2022-05-16 15:10
freq           310         8         310       66                 5
mean           NaN       NaN         NaN      NaN               NaN
std            NaN       NaN         NaN      NaN               NaN
min            NaN       NaN         NaN      NaN               NaN
25%            NaN       NaN         NaN      NaN               NaN
50%            NaN       NaN         NaN      NaN               NaN
75%            NaN       NaN         NaN      NaN               NaN
max            NaN       NaN         NaN      NaN               NaN

            EndDatetime      Duration        Demand
count             72856  72856.000000  72856.000000
unique            66745           NaN           NaN
top     2022-09-22 3:10           NaN           NaN
freq                  5           NaN           NaN
mean                NaN    151.194054     17.444445
std                 NaN    146.430286     13.492728
min                 NaN    -29.000000      0.010000
25%                 NaN     40.000000      7.530000
50%                 NaN    112.000000     14.100000
75%                 NaN    202.000000     23.200000
max                 NaN   1573.000000     97.000000

In [45]:
print(data.shape)

(72856, 13)